name: OML-trabalho-master
channels:
  - conda-forge
dependencies:
  - python=3.12.9
  - pandas
  - scikit-learn
  - fastapi
  - uvicorn
  - mlflow
  - pytest
  - docker-py
  - pip
  - pip:
      - joblib
      - requests